# name: Hello World Workflow
# on:
#   push:
#     branches:
#       - main  # Triggers the workflow on push events to the main branch
#       - feature1
#       - feature2
#   pull_request:
#     branches:
#         -main
# jobs:
#   test-job-1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Hello, World!
#         run: echo "Hello, World!"


# name: sample for revision

# on:
#     push:
#         branches:
#             - main
#             - feature1
# jobs:
#     running-shell-scripts:
#         runs-on: ubuntu-latest

#         steps:
#             - name: stages
#               run: echo "done"
        
