name: Hello World Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello, World!
        run: echo "Hello, World!"
